In [1]:
import numpy as np
import pandas as pd
file = open('catsearchwcluster.csv', 'r')
mags = []
datetimes = []
years = []
months = []
days = []
clus = []
types = []
depths = []
lats = []
longs = []

firstline = True
for line in file:
    if firstline:    #skip first line
        firstline = False
        continue
    data = line.strip().split(',')
    datetime = str(data[0])
    datetimes.append(datetime)
    year = str(data[0])[:4]
    years.append(year)
    month = str(data[0])[5:7]
    months.append(month)
    day = str(data[0])[8:10]
    days.append(day)
    mag = float(data[4])
    mags.append(mag)
    depth = str(data[3])
    depths.append(depth)
    clu = int(data[-1])
    clus.append(clu)
    typ = str('1')
    types.append(typ)
    latitude = float(data[1])
    lats.append(latitude)
    longitude = float(data[2])
    longs.append(longitude)
    
mags = np.asarray(mags)
depths = np.asarray(depths)
datetimes = np.asarray(datetimes)
years = np.asarray(years)
months = np.asarray(months)
days = np.asarray(days)
clus = np.asarray(clus)
types = np.asarray(types)
lats = np.asarray(lats)
longs = np.asarray(longs)

In [2]:
all_data = {'startyear': years, 'startmonth': months, 'startday': days, 'depth': depths, 'mag': mags, 'cluster': clus, 'type': types, 'latitude': lats, 'longitude': longs}

In [3]:
df = pd.DataFrame(all_data)
df.to_csv('earthquakesimplified.csv', index = False)

In [5]:
df2 = df.query('startyear == "2001" and mag >= 6')

In [6]:
df2

        cluster   mag startday startmonth startyear type
325668        6  7.50       01         01      2001    E
325672        6  6.80       01         01      2001    E
325705        6  6.40       02         01      2001    E
325724       11  6.00       02         01      2001    E
325955       11  7.10       09         01      2001    E
326005        5  6.93       10         01      2001    E
326023        5  6.00       11         01      2001    E
326096       14  7.70       13         01      2001    E
326177        2  6.40       15         01      2001    E
326229       10  6.00       16         01      2001    E
326230       10  6.90       16         01      2001    E
326340        0  6.00       19         01      2001    E
326349       11  6.30       19         01      2001    E
326352        3  6.00       19         01      2001    E
326640       13  7.70       26         01      2001    E
326795        6  6.20       29         01      2001    E
326926        5  6.00       01         02      2001    E
327425       14  6.60       13         02      2001    E
327441       10  7.40       13         02      2001    E
327476       11  6.10       14         02      2001    E
327478       11  6.20       14         02      2001    E
327526        6  6.10       16         02      2001    E
327596        5  6.20       17         02      2001    E
327641        2  6.00       18         02      2001    E
327862        6  7.10       24         02      2001    E
327875        6  6.20       24         02      2001    E
327907       13  6.20       25         02      2001    E
327972        7  6.10       26         02      2001    E
328081       11  6.70       28         02      2001    E
328083       11  6.30       28         02      2001    E
...         ...   ...      ...        ...       ...  ...
337982       14  6.00       17         10      2001    E
338061        6  7.50       19         10      2001    E
338141       11  6.70       21         10      2001    E
338406       11  6.10       26         10      2001    E
338605       11  7.00       31         10      2001    E
338855       11  6.30       05         11      2001    E
338995       14  6.10       09         11      2001    E
339204        0  6.10       13         11      2001    E
339209        7  6.00       13         11      2001    E
339210        7  6.00       13         11      2001    E
339260       13  7.80       14         11      2001    E
339302        9  6.30       15         11      2001    E
339543        6  6.20       20         11      2001    E
339609       11  6.30       22         11      2001    E
339610       11  6.20       22         11      2001    E
339650       13  6.10       23         11      2001    E
339782       11  6.00       27         11      2001    E
339853        0  6.40       28         11      2001    E
340038       11  6.00       02         12      2001    E
340056        7  6.50       02         12      2001    E
340094       11  6.40       03         12      2001    E
340368        8  6.20       08         12      2001    E
340430        6  6.10       09         12      2001    E
340533       11  6.10       12         12      2001    E
340535        6  7.10       12         12      2001    E
340777        8  6.80       18         12      2001    E
340961       11  6.00       22         12      2001    E
341034       11  6.80       23         12      2001    E
341190       11  6.20       27         12      2001    E
341252       14  6.00       28         12      2001    E

[138 rows x 6 columns]

In [9]:
df2.to_csv('2001magbigger6.csv', index = False)