In [6]:
import numpy as np
import pandas as pd
file = open('catsearch1.csv', 'r')
mags = []
datetimes = []
years = []
months = []
days = []
clus = []
types = []

firstline = True
for line in file:
    if firstline:    #skip first line
        firstline = False
        continue
    data = line.strip().split(',')
    datetime = str(data[0])
    datetimes.append(datetime)
    year = str(data[0])[:4]
    years.append(year)
    month = str(data[0])[5:7]
    months.append(month)
    day = str(data[0])[8:10]
    days.append(day)
    mag = float(data[1])
    mags.append(mag)
    clu = int(data[4])
    clus.append(clu)
    typ = str('E')
    types.append(typ)
    
mags = np.asarray(mags)
datetimes = np.asarray(datetimes)
years = np.asarray(years)
months = np.asarray(months)
days = np.asarray(days)
clus = np.asarray(clus)
types = np.asarray(types)

In [7]:
all_data = {'startyear': years, 'startmonth': months, 'startday': days, 'mag': mags, 'cluster': clus, 'type': types}

In [8]:
df = pd.DataFrame(all_data)
df

        cluster  mag startday startmonth startyear type
0             2  6.9       11         10      1898    E
1             2  7.2       14         07      1899    E
2             2  8.3       04         09      1899    E
3             2  6.9       04         09      1899    E
4             2  7.8       10         09      1899    E
5             2  8.6       10         09      1899    E
6             2  6.9       17         09      1899    E
7             2  6.9       23         09      1899    E
8             2  7.0       23         09      1899    E
9             2  6.8       29         09      1899    E
10            2  8.3       10         10      1900    E
11            2  7.1       18         01      1901    E
12            2  6.6       30         12      1901    E
13            2  7.8       31         12      1901    E
14            2  7.8       01         01      1902    E
15            2  7.0       17         01      1903    E
16            1  6.8       05         02      1903    E
17            2  8.3       02         06      1903    E
18            2  7.8       27         08      1904    E
19            2  7.7       14         02      1905    E
20            1  7.2       22         03      1905    E
21            1  7.4       15         09      1905    E
22            2  7.0       10         12      1905    E
23            1  8.0       17         08      1906    E
24            2  7.6       23         12      1906    E
25            2  6.5       22         08      1907    E
26            1  7.7       02         09      1907    E
27            2  7.1       15         05      1908    E
28            1  7.0       10         04      1909    E
29            2  7.4       08         09      1909    E
...         ...  ...      ...        ...       ...  ...
617839        8  4.6       04         07      2016    E
617840        7  4.9       04         07      2016    E
617841        6  4.2       04         07      2016    E
617842        1  4.6       04         07      2016    E
617843        9  4.4       04         07      2016    E
617844        0  4.7       04         07      2016    E
617845        4  4.3       04         07      2016    E
617846        1  4.4       04         07      2016    E
617847        0  5.0       05         07      2016    E
617848        4  3.0       05         07      2016    E
617849        6  4.4       05         07      2016    E
617850        9  4.5       05         07      2016    E
617851        1  4.8       05         07      2016    E
617852        9  4.4       05         07      2016    E
617853        5  3.1       05         07      2016    E
617854        1  5.2       05         07      2016    E
617855        6  4.3       05         07      2016    E
617856        5  3.5       05         07      2016    E
617857        0  4.3       05         07      2016    E
617858        8  5.2       05         07      2016    E
617859        9  4.3       05         07      2016    E
617860        5  3.5       05         07      2016    E
617861        6  4.4       05         07      2016    E
617862        1  4.6       05         07      2016    E
617863        5  4.3       05         07      2016    E
617864        1  4.4       05         07      2016    E
617865        7  4.8       06         07      2016    E
617866        8  5.9       06         07      2016    E
617867        2  3.8       06         07      2016    E
617868        4  4.3       06         07      2016    E

[617869 rows x 6 columns]

In [12]:
df2 = df.query('startyear == "2001" and mag >= 6')

In [13]:
df2

        cluster   mag startday startmonth startyear type
325667        9  7.50       01         01      2001    E
325671        9  6.80       01         01      2001    E
325704        9  6.40       02         01      2001    E
325723        7  6.00       02         01      2001    E
325954        7  7.10       09         01      2001    E
326004        2  6.93       10         01      2001    E
326022        5  6.00       11         01      2001    E
326095        4  7.70       13         01      2001    E
326176        9  6.40       15         01      2001    E
326228        9  6.00       16         01      2001    E
326229        9  6.90       16         01      2001    E
326339        4  6.00       19         01      2001    E
326348        7  6.30       19         01      2001    E
326351        0  6.00       19         01      2001    E
326639        6  7.70       26         01      2001    E
326794        9  6.20       29         01      2001    E
326925        2  6.00       01         02      2001    E
327424        4  6.60       13         02      2001    E
327440        9  7.40       13         02      2001    E
327475        7  6.10       14         02      2001    E
327477        7  6.20       14         02      2001    E
327525        9  6.10       16         02      2001    E
327595        5  6.20       17         02      2001    E
327640        6  6.00       18         02      2001    E
327861        9  7.10       24         02      2001    E
327874        9  6.20       24         02      2001    E
327906        6  6.20       25         02      2001    E
327971        1  6.10       26         02      2001    E
328080        7  6.70       28         02      2001    E
328082        7  6.30       28         02      2001    E
...         ...   ...      ...        ...       ...  ...
337981        4  6.00       17         10      2001    E
338060        9  7.50       19         10      2001    E
338140        7  6.70       21         10      2001    E
338405        7  6.10       26         10      2001    E
338604        7  7.00       31         10      2001    E
338854        8  6.30       05         11      2001    E
338994        4  6.10       09         11      2001    E
339203        5  6.10       13         11      2001    E
339208        1  6.00       13         11      2001    E
339209        1  6.00       13         11      2001    E
339259        6  7.80       14         11      2001    E
339301        3  6.30       15         11      2001    E
339542        9  6.20       20         11      2001    E
339608        7  6.30       22         11      2001    E
339609        7  6.20       22         11      2001    E
339649        6  6.10       23         11      2001    E
339781        8  6.00       27         11      2001    E
339852        4  6.40       28         11      2001    E
340037        7  6.00       02         12      2001    E
340055        1  6.50       02         12      2001    E
340093        8  6.40       03         12      2001    E
340367        1  6.20       08         12      2001    E
340429        9  6.10       09         12      2001    E
340532        7  6.10       12         12      2001    E
340534        9  7.10       12         12      2001    E
340776        9  6.80       18         12      2001    E
340960        7  6.00       22         12      2001    E
341033        7  6.80       23         12      2001    E
341189        7  6.20       27         12      2001    E
341251        4  6.00       28         12      2001    E

[138 rows x 6 columns]

In [14]:
df2.to_csv('2001magbigger6.csv')