In [1]:
import numpy as np
import pandas as pd
from geopy.distance import vincenty

file = open('centroids.csv', 'r')
centroids =[]

firstline = True
for line in file:
    if firstline:    #skip first line
        firstline = False
        continue
    data = line.strip().split(',')
    centroid = (float (data[2]), float(data[1]))
    centroids.append(centroid)
    
centroids = np.asarray(centroids)
print(centroids)

[[  33.97690806 -103.84817433]
 [  18.29197728  144.18268752]
 [ -32.52261091   64.59844582]
 [ -32.00092431  -65.33982343]
 [ -26.15276467  -98.52347067]
 [  58.92534284 -145.6836834 ]
 [  -1.07717628  127.39010672]
 [  40.33913649  143.83478266]
 [  26.50213992  119.75316817]
 [  37.1633526     9.15232454]
 [  -0.45323712   99.88364793]
 [  -9.73360673  158.6838855 ]
 [  50.50845778  -97.39306083]
 [  33.39597212   69.93868778]
 [  14.61933101  -70.41610456]]

In [2]:
df1 = pd.read_csv('catsearch.csv', dtype = object)
df1

,DateTime,Latitude,Longitude,Depth,Magnitude,MagType,NbStations,Gap,Distance,RMS,Source,EventID
0,1898/06/29 18:36:00.00,52.0000,172.0000,0.00,7.60,ML,0,NaN,NaN,NaN,AK,NaN
1,1898/10/11 16:37:32.70,50.7100,-179.5000,0.00,6.90,ML,0,NaN,NaN,NaN,AK,NaN
2,1899/07/14 13:32:00.00,60.0000,-150.0000,0.00,7.20,ML,0,NaN,NaN,NaN,AK,NaN
3,1899/09/04 00:22:00.00,60.0000,-142.0000,25.00,8.30,ML,0,NaN,NaN,NaN,AK,NaN
4,1899/09/04 04:40:00.00,60.0000,-142.0000,0.00,6.90,ML,0,NaN,NaN,NaN,AK,NaN
5,1899/09/10 17:25:00.00,60.0000,-140.0000,25.00,7.80,ML,0,NaN,NaN,NaN,AK,NaN
6,1899/09/10 21:40:00.00,60.0000,-140.0000,25.00,8.60,ML,0,NaN,NaN,NaN,AK,NaN
7,1899/09/17 12:50:00.00,59.0000,-136.0000,0.00,6.90,ML,0,NaN,NaN,NaN,AK,NaN
8,1899/09/23 11:04:00.00,60.0000,-143.0000,0.00,6.90,ML,0,NaN,NaN,NaN,AK,NaN
9,1899/09/23 12:50:00.00,60.0000,-143.0000,0.00,7.00,ML,0,NaN,NaN,NaN,AK,NaN
10,1899/09/29 12:00:00.00,60.0000,-143.0000,0.00,6.80,ML,0,NaN,NaN,NaN,AK,NaN
11,1900/10/10 12:28:17.60,57.0900,-153.4800,0.00,8.30,ML,0,NaN,NaN,NaN,AK,NaN
12,1901/01/18 04:39:00.00,60.0000,-135.0000,0.00,7.10,ML,0,NaN,NaN,NaN,AK,NaN
13,1901/12/30 22:34:00.00,52.0000,-160.0000,0.00,6.60,ML,0,NaN,NaN,NaN,AK,NaN
14,1901/12/31 09:02:43.10,51.4500,-171.0200,0.00,7.80,ML,0,NaN,NaN,NaN,AK,NaN
15,1902/01/01 05:20:14.80,52.3800,-167.4500,0.00,7.80,ML,0,NaN,NaN,NaN,AK,NaN
16,1903/01/17 16:05:07.10,50.8500,-175.1600,0.00,7.00,ML,0,NaN,NaN,NaN,AK,NaN
17,1903/02/05 18:26:00.00,52.0000,175.0000,0.00,6.80,ML,0,NaN,NaN,NaN,AK,NaN
18,1903/06/02 13:17:21.40,61.5600,-158.5400,0.00,8.30,ML,0,NaN,NaN,NaN,AK,NaN
19,1904/08/27 21:56:20.50,64.6200,-148.2300,0.00,7.80,ML,0,NaN,NaN,NaN,AK,NaN
20,1905/02/14 08:46:38.40,50.7300,-178.5500,0.00,7.70,ML,0,NaN,NaN,NaN,AK,NaN
21,1905/03/22 03:38:53.00,51.2800,174.8300,0.00,7.20,ML,0,NaN,NaN,NaN,AK,NaN
22,1905/09/15 06:02:34.30,52.0600,171.4500,0.00,7.40,ML,0,NaN,NaN,NaN,AK,NaN
23,1905/12/10 12:35:14.90,53.8800,-161.6800,0.00,7.00,ML,0,NaN,NaN,NaN,AK,NaN
24,1906/08/17 00:10:47.20,50.7700,179.7300,0.00,8.00,ML,0,NaN,NaN,NaN,AK,NaN
25,1906/12/23 17:22:00.00,53.0000,-165.0000,0.00,7.60,ML,0,NaN,NaN,NaN,AK,NaN
26,1907/08/22 22:24:00.00,57.0000,-161.0000,120.00,6.50,ML,0,NaN,NaN,NaN,AK,NaN
27,1907/09/02 16:01:39.59,52.4400,170.2800,0.00,7.70,ML,0,NaN,NaN,NaN,AK,NaN
28,1908/05/15 08:31:36.00,59.0000,-141.0000,25.00,7.10,ML,0,NaN,NaN,NaN,AK,NaN
29,1909/04/10 19:36:00.00,52.0000,175.0000,0.00,7.00,ML,0,NaN,NaN,NaN,AK,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
617840,2016/07/04 19:32:36.87,-21.5410,-179.1091,591.48,4.60,Mb,NaN,122,5,0.79,us,201607042024
617841,2016/07/04 19:53:57.56,-21.3093,168.6738,6.56,4.90,Mb,NaN,103,1,0.78,us,201607042025
617842,2016/07/04 21:02:39.86,39.5984,73.0680,10.00,4.20,Mb,NaN,112,1,1.21,us,201607042027
617843,2016/07/04 21:15:52.52,29.6131,143.3523,9.10,4.60,Mb,NaN,142,3,0.97,us,201607042028
617844,2016/07/04 21:35:26.15,-2.1018,138.9660,43.29,4.40,Mb,NaN,192,7,0.89,us,201607042029
617845,2016/07/04 23:02:23.48,-20.6978,-69.1784,93.55,4.70,Mb,NaN,42,0,0.64,us,201607042031
617846,2016/07/04 23:35:14.65,16.6123,-97.8297,31.94,4.30,Mb,NaN,198,1,1.14,us,201607042032
617847,2016/07/04 23:35:51.78,46.8062,152.8785,35.00,4.40,Mb,NaN,169,7,1.41,us,201607042033
617848,2016/07/05 02:29:03.53,-20.1948,-70.9115,11.20,5.00,Mw,NaN,136,1,0.90,us,201607052002
617849,2016/07/05 04:51:12.99,36.1518,-89.6965,9.11,3.00,Md,66,26,4,0.21,NM,NaN
617850,2016/07/05 09:43:44.76,24.8082,95.2124,98.55,4.40,Mb,NaN,64,1,0.57,us,201607052004
617851,2016/07/05 11:18:03.62,-0.2665,125.5466,35.00,4.50,Mb,NaN,51,2,1.01,us,201607052005
617852,2016/07/05 11:33:03.92,35.5119,129.8661,10.00,4.80,Mb,NaN,24,1,0.91,us,201607052006
617853,2016/07/05 11:48:54.10,-0.3386,125.4749,35.00,4.40,Mb,NaN,69,2,1.29,us,201607052007
617854,2016/07/05 14:23:56.30,43.3325,-126.6572,10.00,3.10,ML,NaN,255,2,1.12,us,201607052008
617855,2016/07/05 15:22:17.94,21.8613,145.3276,36.21,5.20,Mb,NaN,34,6,0.48,us,201607052010
617856,2016/07/05 15:52:03.73,38.2305,73.6797,155.40,4.30,Mb,NaN,59,2,0.91,us,201607052011
617857,2016/07/05 17:21:57.21,36.2626,-97.5821,5.00,3.50,Mb,NaN,45,0,0.35,us,201607052012
617858,2016/07/05 18:15:19.69,-41.6855,-74.0542,39.51,4.30,Mb,NaN,161,1,0.68,us,201607052013
617859,2016/07/05 19:06:45.00,-32.9270,-177.8664,10.00,5.20,Mb,NaN,60,4,0.65,us,201607052014
617860,2016/07/05 19:31:44.62,2.0851,128.3228,192.36,4.30,Mb,NaN,105,2,0.60,us,201607052015
617861,2016/07/05 20:17:14.84,37.3679,-98.2025,5.00,3.50,Mb,NaN,121,0,0.23,us,201607052016
617862,2016/07/05 21:00:22.66,39.4890,73.4459,10.00,4.40,Mb,NaN,91,1,1.24,us,201607052017
617863,2016/07/05 23:00:57.63,29.7514,142.1428,29.15,4.60,Mb,NaN,136,3,0.67,us,201607052018
617864,2016/07/05 23:39:17.39,44.1651,-128.9059,10.00,4.30,Mb,NaN,167,4,1.35,us,201607052019
617865,2016/07/05 23:47:28.14,35.7802,140.9868,21.26,4.40,Mb,NaN,125,1,1.27,us,201607052020
617866,2016/07/06 00:27:01.54,-18.8947,169.4241,257.05,4.80,Mb,NaN,81,3,1.08,us,201607062001
617867,2016/07/06 01:01:57.59,-56.8016,-142.1336,10.00,5.90,Mw,NaN,70,27,1.18,us,201607062002
617868,2016/07/06 02:45:17.47,53.4488,-163.4493,10.00,3.80,Mb,NaN,206,1,1.08,us,201607062003
617869,2016/07/06 03:14:56.36,0.1660,-79.8907,35.00,4.30,Mb,NaN,144,1,1.20,us,201607062004

In [3]:
file = open('catsearch.csv', 'r')

points = []
latitudes = []
longitudes = []

firstline = True
for line in file:
    if firstline:    #skip first line
        firstline = False
        continue
    data = line.strip().split(',')    
    point = (float(data[1]), float(data[2]))
    points.append(point)
    latitude = float(data[1])
    latitudes.append(latitude)
    longitude = float(data[2])
    longitudes.append(longitude)
    
points = np.asarray(points)
latitudes = np.asarray(latitudes)
longitudes = np.asarray(longitudes)

In [4]:
from geopy.distance import great_circle
ind = []
for point in points:
    dista = []
    for centroid in centroids:
        dista.append(great_circle(point, centroid).miles)
    ind.append(dista.index(min(dista)))

inds = np.asarray(ind)

In [5]:
df1['cluster'] = inds
df1

,DateTime,Latitude,Longitude,Depth,Magnitude,MagType,NbStations,Gap,Distance,RMS,Source,EventID,cluster
0,1898/06/29 18:36:00.00,52.0000,172.0000,0.00,7.60,ML,0,NaN,NaN,NaN,AK,NaN,7
1,1898/10/11 16:37:32.70,50.7100,-179.5000,0.00,6.90,ML,0,NaN,NaN,NaN,AK,NaN,5
2,1899/07/14 13:32:00.00,60.0000,-150.0000,0.00,7.20,ML,0,NaN,NaN,NaN,AK,NaN,5
3,1899/09/04 00:22:00.00,60.0000,-142.0000,25.00,8.30,ML,0,NaN,NaN,NaN,AK,NaN,5
4,1899/09/04 04:40:00.00,60.0000,-142.0000,0.00,6.90,ML,0,NaN,NaN,NaN,AK,NaN,5
5,1899/09/10 17:25:00.00,60.0000,-140.0000,25.00,7.80,ML,0,NaN,NaN,NaN,AK,NaN,5
6,1899/09/10 21:40:00.00,60.0000,-140.0000,25.00,8.60,ML,0,NaN,NaN,NaN,AK,NaN,5
7,1899/09/17 12:50:00.00,59.0000,-136.0000,0.00,6.90,ML,0,NaN,NaN,NaN,AK,NaN,5
8,1899/09/23 11:04:00.00,60.0000,-143.0000,0.00,6.90,ML,0,NaN,NaN,NaN,AK,NaN,5
9,1899/09/23 12:50:00.00,60.0000,-143.0000,0.00,7.00,ML,0,NaN,NaN,NaN,AK,NaN,5
10,1899/09/29 12:00:00.00,60.0000,-143.0000,0.00,6.80,ML,0,NaN,NaN,NaN,AK,NaN,5
11,1900/10/10 12:28:17.60,57.0900,-153.4800,0.00,8.30,ML,0,NaN,NaN,NaN,AK,NaN,5
12,1901/01/18 04:39:00.00,60.0000,-135.0000,0.00,7.10,ML,0,NaN,NaN,NaN,AK,NaN,5
13,1901/12/30 22:34:00.00,52.0000,-160.0000,0.00,6.60,ML,0,NaN,NaN,NaN,AK,NaN,5
14,1901/12/31 09:02:43.10,51.4500,-171.0200,0.00,7.80,ML,0,NaN,NaN,NaN,AK,NaN,5
15,1902/01/01 05:20:14.80,52.3800,-167.4500,0.00,7.80,ML,0,NaN,NaN,NaN,AK,NaN,5
16,1903/01/17 16:05:07.10,50.8500,-175.1600,0.00,7.00,ML,0,NaN,NaN,NaN,AK,NaN,5
17,1903/02/05 18:26:00.00,52.0000,175.0000,0.00,6.80,ML,0,NaN,NaN,NaN,AK,NaN,5
18,1903/06/02 13:17:21.40,61.5600,-158.5400,0.00,8.30,ML,0,NaN,NaN,NaN,AK,NaN,5
19,1904/08/27 21:56:20.50,64.6200,-148.2300,0.00,7.80,ML,0,NaN,NaN,NaN,AK,NaN,5
20,1905/02/14 08:46:38.40,50.7300,-178.5500,0.00,7.70,ML,0,NaN,NaN,NaN,AK,NaN,5
21,1905/03/22 03:38:53.00,51.2800,174.8300,0.00,7.20,ML,0,NaN,NaN,NaN,AK,NaN,5
22,1905/09/15 06:02:34.30,52.0600,171.4500,0.00,7.40,ML,0,NaN,NaN,NaN,AK,NaN,7
23,1905/12/10 12:35:14.90,53.8800,-161.6800,0.00,7.00,ML,0,NaN,NaN,NaN,AK,NaN,5
24,1906/08/17 00:10:47.20,50.7700,179.7300,0.00,8.00,ML,0,NaN,NaN,NaN,AK,NaN,5
25,1906/12/23 17:22:00.00,53.0000,-165.0000,0.00,7.60,ML,0,NaN,NaN,NaN,AK,NaN,5
26,1907/08/22 22:24:00.00,57.0000,-161.0000,120.00,6.50,ML,0,NaN,NaN,NaN,AK,NaN,5
27,1907/09/02 16:01:39.59,52.4400,170.2800,0.00,7.70,ML,0,NaN,NaN,NaN,AK,NaN,7
28,1908/05/15 08:31:36.00,59.0000,-141.0000,25.00,7.10,ML,0,NaN,NaN,NaN,AK,NaN,5
29,1909/04/10 19:36:00.00,52.0000,175.0000,0.00,7.00,ML,0,NaN,NaN,NaN,AK,NaN,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
617840,2016/07/04 19:32:36.87,-21.5410,-179.1091,591.48,4.60,Mb,NaN,122,5,0.79,us,201607042024,11
617841,2016/07/04 19:53:57.56,-21.3093,168.6738,6.56,4.90,Mb,NaN,103,1,0.78,us,201607042025,11
617842,2016/07/04 21:02:39.86,39.5984,73.0680,10.00,4.20,Mb,NaN,112,1,1.21,us,201607042027,13
617843,2016/07/04 21:15:52.52,29.6131,143.3523,9.10,4.60,Mb,NaN,142,3,0.97,us,201607042028,7
617844,2016/07/04 21:35:26.15,-2.1018,138.9660,43.29,4.40,Mb,NaN,192,7,0.89,us,201607042029,6
617845,2016/07/04 23:02:23.48,-20.6978,-69.1784,93.55,4.70,Mb,NaN,42,0,0.64,us,201607042031,3
617846,2016/07/04 23:35:14.65,16.6123,-97.8297,31.94,4.30,Mb,NaN,198,1,1.14,us,201607042032,0
617847,2016/07/04 23:35:51.78,46.8062,152.8785,35.00,4.40,Mb,NaN,169,7,1.41,us,201607042033,7
617848,2016/07/05 02:29:03.53,-20.1948,-70.9115,11.20,5.00,Mw,NaN,136,1,0.90,us,201607052002,3
617849,2016/07/05 04:51:12.99,36.1518,-89.6965,9.11,3.00,Md,66,26,4,0.21,NM,NaN,0
617850,2016/07/05 09:43:44.76,24.8082,95.2124,98.55,4.40,Mb,NaN,64,1,0.57,us,201607052004,8
617851,2016/07/05 11:18:03.62,-0.2665,125.5466,35.00,4.50,Mb,NaN,51,2,1.01,us,201607052005,6
617852,2016/07/05 11:33:03.92,35.5119,129.8661,10.00,4.80,Mb,NaN,24,1,0.91,us,201607052006,7
617853,2016/07/05 11:48:54.10,-0.3386,125.4749,35.00,4.40,Mb,NaN,69,2,1.29,us,201607052007,6
617854,2016/07/05 14:23:56.30,43.3325,-126.6572,10.00,3.10,ML,NaN,255,2,1.12,us,201607052008,5
617855,2016/07/05 15:22:17.94,21.8613,145.3276,36.21,5.20,Mb,NaN,34,6,0.48,us,201607052010,1
617856,2016/07/05 15:52:03.73,38.2305,73.6797,155.40,4.30,Mb,NaN,59,2,0.91,us,201607052011,13
617857,2016/07/05 17:21:57.21,36.2626,-97.5821,5.00,3.50,Mb,NaN,45,0,0.35,us,201607052012,0
617858,2016/07/05 18:15:19.69,-41.6855,-74.0542,39.51,4.30,Mb,NaN,161,1,0.68,us,201607052013,3
617859,2016/07/05 19:06:45.00,-32.9270,-177.8664,10.00,5.20,Mb,NaN,60,4,0.65,us,201607052014,11
617860,2016/07/05 19:31:44.62,2.0851,128.3228,192.36,4.30,Mb,NaN,105,2,0.60,us,201607052015,6
617861,2016/07/05 20:17:14.84,37.3679,-98.2025,5.00,3.50,Mb,NaN,121,0,0.23,us,201607052016,0
617862,2016/07/05 21:00:22.66,39.4890,73.4459,10.00,4.40,Mb,NaN,91,1,1.24,us,201607052017,13
617863,2016/07/05 23:00:57.63,29.7514,142.1428,29.15,4.60,Mb,NaN,136,3,0.67,us,201607052018,7
617864,2016/07/05 23:39:17.39,44.1651,-128.9059,10.00,4.30,Mb,NaN,167,4,1.35,us,201607052019,5
617865,2016/07/05 23:47:28.14,35.7802,140.9868,21.26,4.40,Mb,NaN,125,1,1.27,us,201607052020,7
617866,2016/07/06 00:27:01.54,-18.8947,169.4241,257.05,4.80,Mb,NaN,81,3,1.08,us,201607062001,11
617867,2016/07/06 01:01:57.59,-56.8016,-142.1336,10.00,5.90,Mw,NaN,70,27,1.18,us,201607062002,4
617868,2016/07/06 02:45:17.47,53.4488,-163.4493,10.00,3.80,Mb,NaN,206,1,1.08,us,201607062003,5
617869,2016/07/06 03:14:56.36,0.1660,-79.8907,35.00,4.30,Mb,NaN,144,1,1.20,us,201607062004,14

In [7]:
df1.to_csv('catsearchwcluster.csv', index = False)

In [2]:
df2 = pd.read_csv('GVP_Eruption_Results.csv', dtype=object)
df2

,Volcano Number,Volcano Name,Eruption Number,Eruption Category,Area of Activity,VEI,VEI Modifier,Start Year Modifier,Start Year,Start Year Uncertainty,...,Evidence Method (dating),End Year Modifier,End Year,End Year Uncertainty,End Month,End Day Modifier,End Day,End Day Uncertainty,Latitude,Longitude
0,241040,White Island,22121,Confirmed Eruption,NaN,1,NaN,NaN,2016,NaN,...,Historical Observations,NaN,2016,NaN,4,NaN,27,NaN,-37.52,177.18
1,390080,Bristol Island,22133,Confirmed Eruption,NaN,1,NaN,NaN,2016,NaN,...,Historical Observations,NaN,2016,NaN,5,NaN,28,NaN,-59.017,-26.533
2,344020,San Cristobal,22130,Confirmed Eruption,NaN,2,NaN,NaN,2016,NaN,...,Historical Observations,NaN,2016,NaN,4,NaN,22,NaN,12.702,-87.004
3,311240,Cleveland,22128,Confirmed Eruption,NaN,0,NaN,NaN,2016,NaN,...,Historical Observations,NaN,2016,NaN,5,NaN,17,NaN,52.825,-169.944
4,357120,Villarrica,22134,Confirmed Eruption,NaN,1,NaN,NaN,2016,NaN,...,Historical Observations,NaN,2016,NaN,4,NaN,3,NaN,-39.42,-71.93
5,252010,Langila,22123,Confirmed Eruption,NaN,2,NaN,NaN,2016,NaN,...,Historical Observations,>,2016,NaN,5,NaN,13,NaN,-5.525,148.42
6,261170,Kerinci,22125,Confirmed Eruption,NaN,2,NaN,NaN,2016,NaN,...,Historical Observations,>,2016,NaN,5,NaN,4,NaN,-1.697,101.264
7,290360,Chikurachki,22127,Confirmed Eruption,NaN,2,NaN,NaN,2016,NaN,...,Historical Observations,NaN,2016,NaN,3,NaN,31,NaN,50.324,155.461
8,312030,Pavlof,22129,Confirmed Eruption,NaN,2,NaN,NaN,2016,NaN,...,Historical Observations,NaN,2016,NaN,5,NaN,20,NaN,55.417,-161.894
9,282110,Asosan,22126,Confirmed Eruption,NaN,1,NaN,NaN,2016,NaN,...,Historical Observations,NaN,2016,NaN,4,NaN,16,NaN,32.884,131.104
10,251020,Manam,22122,Confirmed Eruption,NaN,2,NaN,NaN,2016,NaN,...,Historical Observations,NaN,2016,NaN,3,NaN,4,NaN,-4.08,145.037
11,255020,Bagana,22124,Confirmed Eruption,NaN,2,NaN,NaN,2016,NaN,...,Historical Observations,>,2016,NaN,5,NaN,22,NaN,-6.137,155.196
12,273010,Bulusan,22114,Confirmed Eruption,NaN,2,NaN,NaN,2016,NaN,...,Historical Observations,NaN,2016,NaN,2,NaN,22,NaN,12.77,124.05
13,290390,Alaid,22116,Confirmed Eruption,NaN,1,NaN,NaN,2016,NaN,...,Historical Observations,>,2016,NaN,5,NaN,20,NaN,50.861,155.565
14,345070,Turrialba,22118,Confirmed Eruption,NaN,2,NaN,NaN,2016,NaN,...,Historical Observations,>,2016,NaN,6,NaN,2,NaN,10.025,-83.767
15,343100,San Miguel,22117,Confirmed Eruption,NaN,1,NaN,NaN,2016,NaN,...,Historical Observations,NaN,2016,NaN,1,NaN,18,NaN,13.434,-88.269
16,357070,Chill�n Nevados de,22119,Confirmed Eruption,NaN,2,NaN,NaN,2016,NaN,...,Historical Observations,NaN,2016,NaN,5,NaN,9,NaN,-36.863,-71.377
17,266030,Soputan,22105,Confirmed Eruption,NaN,3,NaN,NaN,2016,NaN,...,Historical Observations,NaN,2016,NaN,2,NaN,7,NaN,1.112,124.737
18,344100,Masaya,22108,Confirmed Eruption,NaN,1,NaN,NaN,2015,NaN,...,Historical Observations,>,2016,NaN,5,NaN,19,NaN,11.984,-86.161
19,211060,Etna,22102,Confirmed Eruption,NaN,2,NaN,NaN,2015,NaN,...,Historical Observations,>,2016,NaN,4,NaN,1,NaN,37.734,15.004
20,344090,Momotombo,22107,Confirmed Eruption,NaN,2,NaN,NaN,2015,NaN,...,Historical Observations,NaN,2016,NaN,4,NaN,7,NaN,12.422,-86.54
21,272020,Kanlaon,22106,Confirmed Eruption,NaN,2,NaN,NaN,2015,NaN,...,Historical Observations,NaN,2016,NaN,3,NaN,31,NaN,10.412,123.132
22,261140,Marapi,22111,Confirmed Eruption,NaN,1,NaN,NaN,2015,NaN,...,Historical Observations,NaN,2015,NaN,11,NaN,14,NaN,-0.381,100.473
23,263310,Tengger Caldera,22103,Confirmed Eruption,Bromo cone,2,NaN,NaN,2015,NaN,...,Historical Observations,>,2016,NaN,5,NaN,24,NaN,-7.942,112.95
24,355100,Lascar,22110,Confirmed Eruption,NaN,2,NaN,NaN,2015,NaN,...,Historical Observations,NaN,2015,NaN,10,NaN,30,NaN,-23.37,-67.73
25,264030,Rinjani,22104,Confirmed Eruption,Barujari crater,2,NaN,NaN,2015,NaN,...,Historical Observations,NaN,2015,NaN,12,NaN,24,NaN,-8.42,116.47
26,345070,Turrialba,22109,Confirmed Eruption,NaN,2,NaN,NaN,2015,NaN,...,Historical Observations,NaN,2015,NaN,10,NaN,30,NaN,10.025,-83.767
27,345020,Rincon de la Vieja,22132,Confirmed Eruption,NaN,1,NaN,NaN,2015,NaN,...,Historical Observations,NaN,2016,NaN,5,NaN,1,NaN,10.83,-85.324
28,357090,Copahue,21098,Confirmed Eruption,Agrio Crater,2,NaN,NaN,2015,NaN,...,Historical Observations,NaN,2016,NaN,3,NaN,26,NaN,-37.856,-71.183
29,290390,Alaid,21096,Confirmed Eruption,NaN,0,NaN,NaN,2015,NaN,...,Historical Observations,NaN,2015,NaN,10,NaN,9,NaN,50.861,155.565
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9743,306030,Ulreung,19654,Confirmed Eruption,NaN,6,NaN,?,-8750,NaN,...,Radiocarbon (corrected),NaN,NaN,NaN,NaN,NaN,NaN,NaN,37.5,130.87
9744,263250,Merapi,15813,Confirmed Eruption,Old Merapi,NaN,NaN,NaN,-8780,150,...,Radiocarbon (corrected),NaN,NaN,NaN,NaN,NaN,NaN,NaN,-7.542,110.442
9745,283230,Akita-Komagatake,18035,Confirmed Eruption,NaN,3,?,NaN,-8800,300,...,Tephrochronology,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39.761,140.799
9746,373060,Askja,12904,Confirmed Eruption,SE part of Askja caldera,5,NaN,NaN,-8910,200,...,Radiocarbon (corrected),NaN,NaN,NaN,NaN,NaN,NaN,NaN,65.033,-16.783
9747,371040,Brennisteinsfjoll,19930,Confirmed Eruption,Heidin H�,0,NaN,?,-9000,NaN,...,Tephrochronology,NaN,NaN,NaN,NaN,NaN,NaN,NaN,63.933,-21.783
9748,324020,Craters of the Moon,21100,Confirmed Eruption,NaN,0,NaN,NaN,-9050,NaN,...,Radiocarbon (uncorrected),NaN,NaN,NaN,NaN,NaN,NaN,NaN,43.42,-113.5
9749,282120,Kujusan,17352,Confirmed Eruption,NaN,4,NaN,NaN,-9160,1190,...,Radiocarbon (corrected),NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.086,131.249
9750,322110,Newberry,20598,Confirmed Eruption,South and east caldera rim,NaN,NaN,NaN,-9210,1200,...,Radiocarbon (corrected),NaN,NaN,NaN,NaN,NaN,NaN,NaN,43.722,-121.229
9751,241070,Taupo,14532,Confirmed Eruption,Acacia Bay lava dome,4,NaN,?,-9210,NaN,...,Tephrochronology,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-38.82,176
9752,241070,Taupo,14531,Confirmed Eruption,4 km W of Te Kohaiakahu Point,5,NaN,NaN,-9240,75,...,Radiocarbon (corrected),NaN,NaN,NaN,NaN,NaN,NaN,NaN,-38.82,176
9753,357122,Lanin,12079,Confirmed Eruption,NaN,NaN,NaN,NaN,-9240,500,...,Radiocarbon (corrected),NaN,NaN,NaN,NaN,NaN,NaN,NaN,-39.637,-71.502
9754,346010,Baru,11249,Confirmed Eruption,NaN,NaN,NaN,NaN,-9280,30,...,Radiocarbon (corrected),NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.808,-82.543
9755,313030,Redoubt,20290,Confirmed Eruption,NaN,NaN,NaN,NaN,-9310,300,...,Varve Count,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.485,-152.742
9756,241080,Tongariro,14558,Confirmed Eruption,Tama Lakes to Te Mari,5,NaN,?,-9350,NaN,...,Tephrochronology,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-39.157,175.632
9757,290360,Chikurachki,20896,Confirmed Eruption,NaN,2,?,NaN,-9360,80,...,Radiocarbon (corrected),NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.324,155.461
9758,341130,Tacana,10611,Confirmed Eruption,NaN,NaN,NaN,NaN,-9450,150,...,Radiocarbon (corrected),NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.132,-92.109
9759,241080,Tongariro,14557,Confirmed Eruption,Saddle cone area to Half Cone,5,NaN,?,-9450,NaN,...,Radiocarbon (corrected),NaN,NaN,NaN,NaN,NaN,NaN,NaN,-39.157,175.632
9760,241070,Taupo,14530,Confirmed Eruption,East-central Lake Taupo (Karapiti),5,NaN,NaN,-9460,200,...,Radiocarbon (corrected),NaN,NaN,NaN,NaN,NaN,NaN,NaN,-38.82,176
9761,283271,Towada,18091,Confirmed Eruption,Nakanoumi,3,NaN,?,-9490,NaN,...,Radiocarbon (corrected),NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.51,140.88
9762,300272,Khangar,19487,Confirmed Eruption,NaN,4,P,NaN,-9500,300,...,Radiocarbon (corrected),NaN,NaN,NaN,NaN,NaN,NaN,NaN,54.761,157.407
9763,373090,Theistareykir,12954,Confirmed Eruption,Theistareykjabunga shield volcano,0,NaN,?,-9500,NaN,...,Tephrochronology,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65.833,-17.166
9764,282050,Kuchinoerabujima,16954,Confirmed Eruption,Furu-take,NaN,NaN,NaN,-9520,300,...,Radiocarbon (corrected),NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.443,130.217
9765,283141,Nantai,17850,Confirmed Eruption,NaN,NaN,NaN,NaN,-9540,500,...,Radiocarbon (corrected),NaN,NaN,NaN,NaN,NaN,NaN,NaN,36.762,139.494
9766,241080,Tongariro,14556,Confirmed Eruption,Saddle Cone to Half Cone,5,NaN,?,-9650,NaN,...,Tephrochronology,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-39.157,175.632
9767,241100,Ruapehu,14607,Confirmed Eruption,NaN,NaN,NaN,?,-9650,NaN,...,Tephrochronology,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-39.28,175.57
9768,241100,Ruapehu,14606,Confirmed Eruption,NaN,NaN,NaN,?,-9850,NaN,...,Radiocarbon (corrected),NaN,NaN,NaN,NaN,NaN,NaN,NaN,-39.28,175.57
9769,241080,Tongariro,14555,Confirmed Eruption,NaN,NaN,NaN,?,-9850,NaN,...,Radiocarbon (corrected),NaN,NaN,NaN,NaN,NaN,NaN,NaN,-39.157,175.632
9770,213020,Nemrut Dagi,13908,Confirmed Eruption,NaN,NaN,NaN,NaN,-9950,150,...,Varve Count,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38.654,42.229
9771,324020,Craters of the Moon,21101,Confirmed Eruption,Sunset cone,0,NaN,NaN,-10060,NaN,...,Radiocarbon (uncorrected),NaN,NaN,NaN,NaN,NaN,NaN,NaN,43.42,-113.5
9772,344020,San Cristobal,22131,Confirmed Eruption,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.702,-87.004

In [4]:
from geopy.distance import great_circle
file = open('GVP_Eruption_Results.csv', 'r')

points = []
latitudes = []
longitudes = []

firstline = True
for line in file:
    if firstline:    #skip first line
        firstline = False
        continue
    data = line.strip().split(',')    
    point = (float(data[-2]), float(data[-1]))
    points.append(point)
    latitude = float(data[-2])
    latitudes.append(latitude)
    longitude = float(data[-1])
    longitudes.append(longitude)
    
points = np.asarray(points)
latitudes = np.asarray(latitudes)
longitudes = np.asarray(longitudes)
ind = []
for point in points:
    dista = []
    for centroid in centroids:
        dista.append(great_circle(point, centroid).miles)
    ind.append(dista.index(min(dista)))

inds = np.asarray(ind)
df2['cluster'] = inds
df2

,Volcano Number,Volcano Name,Eruption Number,Eruption Category,Area of Activity,VEI,VEI Modifier,Start Year Modifier,Start Year,Start Year Uncertainty,...,End Year Modifier,End Year,End Year Uncertainty,End Month,End Day Modifier,End Day,End Day Uncertainty,Latitude,Longitude,cluster
0,241040,White Island,22121,Confirmed Eruption,NaN,1,NaN,NaN,2016,NaN,...,NaN,2016,NaN,4,NaN,27,NaN,-37.52,177.18,11
1,390080,Bristol Island,22133,Confirmed Eruption,NaN,1,NaN,NaN,2016,NaN,...,NaN,2016,NaN,5,NaN,28,NaN,-59.017,-26.533,3
2,344020,San Cristobal,22130,Confirmed Eruption,NaN,2,NaN,NaN,2016,NaN,...,NaN,2016,NaN,4,NaN,22,NaN,12.702,-87.004,14
3,311240,Cleveland,22128,Confirmed Eruption,NaN,0,NaN,NaN,2016,NaN,...,NaN,2016,NaN,5,NaN,17,NaN,52.825,-169.944,5
4,357120,Villarrica,22134,Confirmed Eruption,NaN,1,NaN,NaN,2016,NaN,...,NaN,2016,NaN,4,NaN,3,NaN,-39.42,-71.93,3
5,252010,Langila,22123,Confirmed Eruption,NaN,2,NaN,NaN,2016,NaN,...,>,2016,NaN,5,NaN,13,NaN,-5.525,148.42,11
6,261170,Kerinci,22125,Confirmed Eruption,NaN,2,NaN,NaN,2016,NaN,...,>,2016,NaN,5,NaN,4,NaN,-1.697,101.264,10
7,290360,Chikurachki,22127,Confirmed Eruption,NaN,2,NaN,NaN,2016,NaN,...,NaN,2016,NaN,3,NaN,31,NaN,50.324,155.461,7
8,312030,Pavlof,22129,Confirmed Eruption,NaN,2,NaN,NaN,2016,NaN,...,NaN,2016,NaN,5,NaN,20,NaN,55.417,-161.894,5
9,282110,Asosan,22126,Confirmed Eruption,NaN,1,NaN,NaN,2016,NaN,...,NaN,2016,NaN,4,NaN,16,NaN,32.884,131.104,8
10,251020,Manam,22122,Confirmed Eruption,NaN,2,NaN,NaN,2016,NaN,...,NaN,2016,NaN,3,NaN,4,NaN,-4.08,145.037,11
11,255020,Bagana,22124,Confirmed Eruption,NaN,2,NaN,NaN,2016,NaN,...,>,2016,NaN,5,NaN,22,NaN,-6.137,155.196,11
12,273010,Bulusan,22114,Confirmed Eruption,NaN,2,NaN,NaN,2016,NaN,...,NaN,2016,NaN,2,NaN,22,NaN,12.77,124.05,6
13,290390,Alaid,22116,Confirmed Eruption,NaN,1,NaN,NaN,2016,NaN,...,>,2016,NaN,5,NaN,20,NaN,50.861,155.565,7
14,345070,Turrialba,22118,Confirmed Eruption,NaN,2,NaN,NaN,2016,NaN,...,>,2016,NaN,6,NaN,2,NaN,10.025,-83.767,14
15,343100,San Miguel,22117,Confirmed Eruption,NaN,1,NaN,NaN,2016,NaN,...,NaN,2016,NaN,1,NaN,18,NaN,13.434,-88.269,14
16,357070,Chill�n Nevados de,22119,Confirmed Eruption,NaN,2,NaN,NaN,2016,NaN,...,NaN,2016,NaN,5,NaN,9,NaN,-36.863,-71.377,3
17,266030,Soputan,22105,Confirmed Eruption,NaN,3,NaN,NaN,2016,NaN,...,NaN,2016,NaN,2,NaN,7,NaN,1.112,124.737,6
18,344100,Masaya,22108,Confirmed Eruption,NaN,1,NaN,NaN,2015,NaN,...,>,2016,NaN,5,NaN,19,NaN,11.984,-86.161,14
19,211060,Etna,22102,Confirmed Eruption,NaN,2,NaN,NaN,2015,NaN,...,>,2016,NaN,4,NaN,1,NaN,37.734,15.004,9
20,344090,Momotombo,22107,Confirmed Eruption,NaN,2,NaN,NaN,2015,NaN,...,NaN,2016,NaN,4,NaN,7,NaN,12.422,-86.54,14
21,272020,Kanlaon,22106,Confirmed Eruption,NaN,2,NaN,NaN,2015,NaN,...,NaN,2016,NaN,3,NaN,31,NaN,10.412,123.132,6
22,261140,Marapi,22111,Confirmed Eruption,NaN,1,NaN,NaN,2015,NaN,...,NaN,2015,NaN,11,NaN,14,NaN,-0.381,100.473,10
23,263310,Tengger Caldera,22103,Confirmed Eruption,Bromo cone,2,NaN,NaN,2015,NaN,...,>,2016,NaN,5,NaN,24,NaN,-7.942,112.95,10
24,355100,Lascar,22110,Confirmed Eruption,NaN,2,NaN,NaN,2015,NaN,...,NaN,2015,NaN,10,NaN,30,NaN,-23.37,-67.73,3
25,264030,Rinjani,22104,Confirmed Eruption,Barujari crater,2,NaN,NaN,2015,NaN,...,NaN,2015,NaN,12,NaN,24,NaN,-8.42,116.47,6
26,345070,Turrialba,22109,Confirmed Eruption,NaN,2,NaN,NaN,2015,NaN,...,NaN,2015,NaN,10,NaN,30,NaN,10.025,-83.767,14
27,345020,Rincon de la Vieja,22132,Confirmed Eruption,NaN,1,NaN,NaN,2015,NaN,...,NaN,2016,NaN,5,NaN,1,NaN,10.83,-85.324,14
28,357090,Copahue,21098,Confirmed Eruption,Agrio Crater,2,NaN,NaN,2015,NaN,...,NaN,2016,NaN,3,NaN,26,NaN,-37.856,-71.183,3
29,290390,Alaid,21096,Confirmed Eruption,NaN,0,NaN,NaN,2015,NaN,...,NaN,2015,NaN,10,NaN,9,NaN,50.861,155.565,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9743,306030,Ulreung,19654,Confirmed Eruption,NaN,6,NaN,?,-8750,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37.5,130.87,7
9744,263250,Merapi,15813,Confirmed Eruption,Old Merapi,NaN,NaN,NaN,-8780,150,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-7.542,110.442,10
9745,283230,Akita-Komagatake,18035,Confirmed Eruption,NaN,3,?,NaN,-8800,300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39.761,140.799,7
9746,373060,Askja,12904,Confirmed Eruption,SE part of Askja caldera,5,NaN,NaN,-8910,200,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65.033,-16.783,9
9747,371040,Brennisteinsfjoll,19930,Confirmed Eruption,Heidin H�,0,NaN,?,-9000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,63.933,-21.783,9
9748,324020,Craters of the Moon,21100,Confirmed Eruption,NaN,0,NaN,NaN,-9050,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,43.42,-113.5,0
9749,282120,Kujusan,17352,Confirmed Eruption,NaN,4,NaN,NaN,-9160,1190,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.086,131.249,8
9750,322110,Newberry,20598,Confirmed Eruption,South and east caldera rim,NaN,NaN,NaN,-9210,1200,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,43.722,-121.229,0
9751,241070,Taupo,14532,Confirmed Eruption,Acacia Bay lava dome,4,NaN,?,-9210,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-38.82,176,11
9752,241070,Taupo,14531,Confirmed Eruption,4 km W of Te Kohaiakahu Point,5,NaN,NaN,-9240,75,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-38.82,176,11
9753,357122,Lanin,12079,Confirmed Eruption,NaN,NaN,NaN,NaN,-9240,500,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-39.637,-71.502,3
9754,346010,Baru,11249,Confirmed Eruption,NaN,NaN,NaN,NaN,-9280,30,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.808,-82.543,14
9755,313030,Redoubt,20290,Confirmed Eruption,NaN,NaN,NaN,NaN,-9310,300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.485,-152.742,5
9756,241080,Tongariro,14558,Confirmed Eruption,Tama Lakes to Te Mari,5,NaN,?,-9350,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-39.157,175.632,11
9757,290360,Chikurachki,20896,Confirmed Eruption,NaN,2,?,NaN,-9360,80,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.324,155.461,7
9758,341130,Tacana,10611,Confirmed Eruption,NaN,NaN,NaN,NaN,-9450,150,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.132,-92.109,14
9759,241080,Tongariro,14557,Confirmed Eruption,Saddle cone area to Half Cone,5,NaN,?,-9450,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-39.157,175.632,11
9760,241070,Taupo,14530,Confirmed Eruption,East-central Lake Taupo (Karapiti),5,NaN,NaN,-9460,200,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-38.82,176,11
9761,283271,Towada,18091,Confirmed Eruption,Nakanoumi,3,NaN,?,-9490,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.51,140.88,7
9762,300272,Khangar,19487,Confirmed Eruption,NaN,4,P,NaN,-9500,300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,54.761,157.407,7
9763,373090,Theistareykir,12954,Confirmed Eruption,Theistareykjabunga shield volcano,0,NaN,?,-9500,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65.833,-17.166,9
9764,282050,Kuchinoerabujima,16954,Confirmed Eruption,Furu-take,NaN,NaN,NaN,-9520,300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.443,130.217,8
9765,283141,Nantai,17850,Confirmed Eruption,NaN,NaN,NaN,NaN,-9540,500,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36.762,139.494,7
9766,241080,Tongariro,14556,Confirmed Eruption,Saddle Cone to Half Cone,5,NaN,?,-9650,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-39.157,175.632,11
9767,241100,Ruapehu,14607,Confirmed Eruption,NaN,NaN,NaN,?,-9650,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-39.28,175.57,11
9768,241100,Ruapehu,14606,Confirmed Eruption,NaN,NaN,NaN,?,-9850,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-39.28,175.57,11
9769,241080,Tongariro,14555,Confirmed Eruption,NaN,NaN,NaN,?,-9850,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-39.157,175.632,11
9770,213020,Nemrut Dagi,13908,Confirmed Eruption,NaN,NaN,NaN,NaN,-9950,150,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38.654,42.229,13
9771,324020,Craters of the Moon,21101,Confirmed Eruption,Sunset cone,0,NaN,NaN,-10060,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,43.42,-113.5,0
9772,344020,San Cristobal,22131,Confirmed Eruption,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.702,-87.004,14

In [5]:
df2.to_csv('volcluster.csv', index = False)

In [12]:
cols = df2.columns
cols = cols.map(lambda x: x.replace(' ', '_') if isinstance(x, (str, unicode)) else x)
df2.columns = cols
#replace space with _ in df
df3 = df2.query('Start_Year == "2001"')
#'Start Year' == 2001
df3

,Volcano_Number,Volcano_Name,Eruption_Number,Eruption_Category,Area_of_Activity,VEI,VEI_Modifier,Start_Year_Modifier,Start_Year,Start_Year_Uncertainty,...,End_Year_Modifier,End_Year,End_Year_Uncertainty,End_Month,End_Day_Modifier,End_Day,End_Day_Uncertainty,Latitude,Longitude,cluster
562,300250,Bezymianny,19379,Confirmed Eruption,NaN,2,NaN,NaN,2001,NaN,...,NaN,2002,NaN,1,?,6,NaN,55.972,160.595,7
563,360160,Kick 'em Jenny,12468,Confirmed Eruption,NaN,0,NaN,NaN,2001,NaN,...,NaN,2001,NaN,12,NaN,6,NaN,12.3,-61.64,14
564,211060,Etna,13835,Confirmed Eruption,Central Crater NE Crater,1,NaN,NaN,2001,NaN,...,NaN,2002,NaN,10,?,30,NaN,37.734,15.004,9
565,352020,Guagua Pichincha,11497,Confirmed Eruption,North of 1981 crater,1,?,NaN,2001,NaN,...,NaN,2001,NaN,11,NaN,26,NaN,-0.171,-78.598,14
566,385052,Unnamed,13144,Confirmed Eruption,Seamount NW of W�st seamount,0,NaN,NaN,2001,NaN,...,NaN,2002,NaN,3,NaN,0,NaN,-32.958,-5.22,3
567,300130,Karymsky,19187,Confirmed Eruption,Summit and upper south flank,3,NaN,NaN,2001,NaN,...,NaN,2014,NaN,10,NaN,4,NaN,54.049,159.443,7
568,342110,Pacaya,19880,Confirmed Eruption,MacKenney Crater,1,NaN,NaN,2001,NaN,...,NaN,2001,NaN,10,NaN,31,NaN,14.381,-90.601,14
569,300100,Avachinsky,19104,Confirmed Eruption,NaN,1,NaN,NaN,2001,NaN,...,NaN,2001,NaN,10,NaN,5,NaN,53.256,158.836,7
570,390081,Montagu Island,13205,Confirmed Eruption,NW of Mount Belinda,1,?,NaN,2001,NaN,...,NaN,2007,NaN,9,NaN,20,NaN,-58.445,-26.374,3
571,243091,Unnamed,14772,Confirmed Eruption,NaN,2,NaN,NaN,2001,NaN,...,NaN,2001,NaN,9,?,28,NaN,-18.325,-174.365,11
572,261160,Talang,15494,Confirmed Eruption,Kepundan Panjang & Kabuo Gabuo Atas,1,NaN,NaN,2001,NaN,...,NaN,2001,NaN,11,NaN,15,3,-0.978,100.679,10
573,284120,Ioto,18421,Confirmed Eruption,Off SE coast and Idogahama (NW coast),1,NaN,NaN,2001,NaN,...,NaN,2001,NaN,10,NaN,23,NaN,24.751,141.289,1
574,390090,Saunders,13217,Confirmed Eruption,NaN,0,NaN,NaN,2001,NaN,...,NaN,2001,NaN,11,?,0,NaN,-57.8,-26.483,3
575,252120,Ulawun,15065,Confirmed Eruption,NaN,2,NaN,NaN,2001,NaN,...,NaN,2001,NaN,8,NaN,28,NaN,-5.05,151.33,11
576,300250,Bezymianny,19378,Confirmed Eruption,NaN,3,NaN,NaN,2001,NaN,...,NaN,2001,NaN,8,?,10,NaN,55.972,160.595,7
577,262000,Krakatau,15625,Confirmed Eruption,Anak Krakatau,1,NaN,NaN,2001,NaN,...,NaN,2001,NaN,9,?,17,NaN,-6.102,105.423,10
578,211060,Etna,13832,Confirmed Eruption,S to NE flanks (3100-2100 m),2,NaN,NaN,2001,NaN,...,NaN,2001,NaN,8,NaN,9,NaN,37.734,15.004,9
579,251020,Manam,14929,Confirmed Eruption,NaN,2,NaN,NaN,2001,NaN,...,NaN,2001,NaN,6,?,25,NaN,-4.08,145.037,11
580,233020,Fournaise Piton de la,14381,Confirmed Eruption,ESE flank (2500 m) East flank (1800-2000 m),1,NaN,NaN,2001,NaN,...,NaN,2001,NaN,7,NaN,7,NaN,-21.244,55.708,2
581,257050,Lopevi,15317,Confirmed Eruption,NW flank (200-400 m),3,NaN,NaN,2001,NaN,...,NaN,2001,NaN,6,>,19,NaN,-16.507,168.346,11
582,268030,Ibu,16580,Confirmed Eruption,NaN,0,NaN,NaN,2001,NaN,...,NaN,2001,NaN,10,?,3,NaN,1.488,127.63,6
583,261170,Kerinci,15528,Confirmed Eruption,NaN,2,NaN,NaN,2001,NaN,...,NaN,2002,NaN,8,?,27,NaN,-1.697,101.264,10
584,344020,San Cristobal,10888,Confirmed Eruption,NaN,1,NaN,NaN,2001,NaN,...,NaN,2001,NaN,12,?,9,NaN,12.702,-87.004,14
585,234011,McDonald Islands,14397,Confirmed Eruption,NaN,1,?,NaN,2001,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-53.03,72.6,2
586,284141,Ahyi,18474,Confirmed Eruption,20.34�N 145.02�E,0,NaN,NaN,2001,NaN,...,NaN,2001,NaN,4,NaN,25,NaN,20.42,145.03,1
587,344100,Masaya,11037,Confirmed Eruption,Santiago,1,NaN,NaN,2001,NaN,...,NaN,2001,NaN,4,?,25,NaN,11.984,-86.161,14
588,261140,Marapi,15478,Confirmed Eruption,Verbeek Crater,2,NaN,NaN,2001,NaN,...,NaN,2001,NaN,6,NaN,5,NaN,-0.381,100.473,10
589,233020,Fournaise Piton de la,14380,Confirmed Eruption,South flank (below Dolomieu at ~2500 m),1,NaN,NaN,2001,NaN,...,NaN,2001,NaN,4,NaN,4,NaN,-21.244,55.708,2
590,241040,White Island,14495,Confirmed Eruption,MH vent,2,NaN,NaN,2001,NaN,...,NaN,2001,NaN,2,?,19,NaN,-37.52,177.18,11
591,223020,Nyamuragira,14081,Confirmed Eruption,North and SSE flanks,2,?,NaN,2001,NaN,...,NaN,2001,NaN,4,NaN,5,4,-1.408,29.2,9
592,311240,Cleveland,19816,Confirmed Eruption,NaN,3,?,NaN,2001,NaN,...,NaN,2001,NaN,4,?,15,NaN,52.825,-169.944,5
593,344040,Telica,10935,Confirmed Eruption,NaN,1,NaN,NaN,2001,NaN,...,NaN,2001,NaN,12,?,19,NaN,12.602,-86.845,14
594,252120,Ulawun,15064,Confirmed Eruption,Summit and NNE flank,3,NaN,NaN,2001,NaN,...,NaN,2001,NaN,5,NaN,3,NaN,-5.05,151.33,11
595,264090,Inielika,16258,Confirmed Eruption,Summit crater complex,2,NaN,NaN,2001,NaN,...,NaN,2001,NaN,3,?,0,NaN,-8.73,120.98,6
596,284040,Miyakejima,18274,Confirmed Eruption,NaN,2,NaN,NaN,2001,NaN,...,NaN,2002,NaN,11,NaN,24,NaN,34.094,139.526,7
597,273030,Mayon,16810,Confirmed Eruption,NaN,3,NaN,NaN,2001,NaN,...,NaN,2001,NaN,8,NaN,8,NaN,13.257,123.685,8

In [14]:
df3.to_csv('2001volcanoes.csv', index = False)