In [1]:
import numpy as np
import pandas as pd
from geopy.distance import vincenty

file = open('centroids.csv', 'r')
centroids =[]

firstline = True
for line in file:
    if firstline:    #skip first line
        firstline = False
        continue
    data = line.strip().split(',')
    centroid = (float (data[0]), float(data[1]))
    centroids.append(centroid)
    
centroids = np.asarray(centroids)

In [2]:

file = open('GVP_Eruption_Results.csv', 'r')

points = []
numbers = []
names = []
styears = []
stmonths = []
stdays = []
edyears = []
edmonths = []
eddays = []
veis = []
latitudes = []
longitudes = []

firstline = True
for line in file:
    if firstline:    #skip first line
        firstline = False
        continue
    data = line.strip().split(',')    
    point = (float(data[-2]), float(data[-1]))
    points.append(point)
    latitude = float(data[-2])
    latitudes.append(latitude)
    longitude = float(data[-1])
    longitudes.append(longitude)
    number = int(data[0])
    numbers.append(number)
    name = str(data[1])
    names.append(name)
    vei = str(data[5])
    veis.append(vei)
    styear = str(data[8])
    styears.append(styear)
    stmonth = str(data[10])
    stmonths.append(stmonth)
    stday = str(data[12])
    stdays.append(stday)
    

points = np.asarray(points)
numbers = np.asarray(numbers)
names = np.asarray(names)
veis = np.asarray(veis)
styars = np.asarray(styears)
stmonths = np.asarray(stmonths)
stdays = np.asarray(stdays)
latitudes = np.asarray(latitudes)
longitudes = np.asarray(longitudes)

In [3]:
ind = []
for point in points:
    dista = []
    for centroid in centroids:
        dista.append(vincenty(point, centroid).miles)
    ind.append(dista.index(min(dista)))

inds = np.asarray(ind)

In [4]:
all_data = {'startyear': styears, 'startmonth': stmonths, 'startday': stdays, 'VEI': veis, 'latitude': latitudes, 'longitude': longitudes, 'cluster': inds}
df = pd.DataFrame(all_data)
df

     VEI  cluster  latitude  longitude startday startmonth startyear
0      1        8   -37.520    177.180       27          4      2016
1      1        0   -59.017    -26.533       24          4      2016
2      2        4    12.702    -87.004       22          4      2016
3      0        2    52.825   -169.944       16          4      2016
4      1        0   -39.420    -71.930        3          4      2016
5      2        7    -5.525    148.420        2          4      2016
6      2        9    -1.697    101.264       31          3      2016
7      2        1    50.324    155.461       29          3      2016
8      2        2    55.417   -161.894       27          3      2016
9      1        1    32.884    131.104        4          3      2016
10     2        7    -4.080    145.037        4          3      2016
11     2        7    -6.137    155.196        3          3      2016
12     2        9    12.770    124.050       22          2      2016
13     1        1    50.861    155.565       21          2      2016
14     2        4    10.025    -83.767        2          2      2016
15     1        4    13.434    -88.269       12          1      2016
16     2        0   -36.863    -71.377        8          1      2016
17     3        9     1.112    124.737        2          1      2016
18     1        4    11.984    -86.161       11         12      2015
19     2        3    37.734     15.004        2         12      2015
20     2        4    12.422    -86.540        1         12      2015
21     2        9    10.412    123.132       24         11      2015
22     1        9    -0.381    100.473       14         11      2015
23     2        9    -7.942    112.950       12         11      2015
24     2        0   -23.370    -67.730       30         10      2015
25     2        9    -8.420    116.470       25         10      2015
26     2        4    10.025    -83.767       23         10      2015
27     1        4    10.830    -85.324       17         10      2015
28     2        0   -37.856    -71.183        6         10      2015
29     0        1    50.861    155.565        2         10      2015
...   ..      ...       ...        ...      ...        ...       ...
9743   6        1    37.500    130.870        0          0     -8750
9744            9    -7.542    110.442        0          0     -8780
9745   3        1    39.761    140.799        0          0     -8800
9746   5        3    65.033    -16.783        0          0     -8910
9747   0        3    63.933    -21.783        0          0     -9000
9748   0        5    43.420   -113.500                         -9050
9749   4        1    33.086    131.249        0          0     -9160
9750            5    43.722   -121.229        0          0     -9210
9751   4        8   -38.820    176.000        0          0     -9210
9752   5        8   -38.820    176.000        0          0     -9240
9753            0   -39.637    -71.502        0          0     -9240
9754            4     8.808    -82.543        0          0     -9280
9755            2    60.485   -152.742        0          0     -9310
9756   5        8   -39.157    175.632        0          0     -9350
9757   2        1    50.324    155.461                         -9360
9758            4    15.132    -92.109        0          0     -9450
9759   5        8   -39.157    175.632        0          0     -9450
9760   5        8   -38.820    176.000        0          0     -9460
9761   3        1    40.510    140.880        0          0     -9490
9762   4        1    54.761    157.407        0          0     -9500
9763   0        3    65.833    -17.166        0          0     -9500
9764            1    30.443    130.217        0          0     -9520
9765            1    36.762    139.494        0          0     -9540
9766   5        8   -39.157    175.632        0          0     -9650
9767            8   -39.280    175.570        0          0     -9650
9768            8   -39.280    175.570        0          0     -9850
9769            8   -39.157    175.632        0          0     -9850
9770            3    38.654     42.229        0          0     -9950
9771   0        5    43.420   -113.500                        -10060
9772            4    12.702    -87.004

[9773 rows x 7 columns]

In [5]:
df.to_csv('volcluster.csv')

In [6]:
df2 = df.query('startyear == "2001"')
df2

    VEI  cluster  latitude  longitude startday startmonth startyear
562   2        1    55.972    160.595       10         12      2001
563   0        4    12.300    -61.640        4         12      2001
564   1        3    37.734     15.004        0         12      2001
565   1        4    -0.171    -78.598       26         11      2001
566   0        0   -32.958     -5.220       24         11      2001
567   3        1    54.049    159.443       15         11      2001
568   1        4    14.381    -90.601       31         10      2001
569   1        1    53.256    158.836        5         10      2001
570   1        0   -58.445    -26.374        1         10      2001
571   2        8   -18.325   -174.365       27          9      2001
572   1        9    -0.978    100.679       25          9      2001
573   1        1    24.751    141.289       21          9      2001
574   0        0   -57.800    -26.483        0          9      2001
575   2        7    -5.050    151.330       28          8      2001
576   3        1    55.972    160.595       23          7      2001
577   1        9    -6.102    105.423       21          7      2001
578   2        3    37.734     15.004       17          7      2001
579   2        7    -4.080    145.037       14          6      2001
580   1        6   -21.244     55.708       11          6      2001
581   3        7   -16.507    168.346        8          6      2001
582   0        9     1.488    127.630       28          5      2001
583   2        9    -1.697    101.264       12          5      2001
584   1        4    12.702    -87.004       11          5      2001
585   1        9   -53.030     72.600        3          5      2001
586   0        1    20.420    145.030       24          4      2001
587   1        4    11.984    -86.161       23          4      2001
588   2        9    -0.381    100.473       13          4      2001
589   1        6   -21.244     55.708       27          3      2001
590   2        8   -37.520    177.180       19          2      2001
591   2        3    -1.408     29.200        6          2      2001
592   3        2    52.825   -169.944        2          2      2001
593   1        4    12.602    -86.845       17          1      2001
594   3        7    -5.050    151.330       16          1      2001
595   2        9    -8.730    120.980       11          1      2001
596   2        1    34.094    139.526       11          1      2001
597   3        9    13.257    123.685        8          1      2001

In [9]:
df2.to_csv('2001volcanoes.csv')